name: system-monitor
base: core26 # Atualizado para a base do Ubuntu 26.04 LTS
version: '0.1.0'
summary: Monitor de Sistema feito em Flutter
description: |
  Um aplicativo para monitoramento de recursos do sistema,
  incluindo CPU, uso de disco, redes e processos.

grade: stable
confinement: strict

apps:
  system-monitor:
    command: bin/system_monitor
    extensions: [gnome] # Ativa o suporte ao toolkit gráfico do ecossistema Ubuntu 26.04
    plugs:
      - network
      - home
      - system-observe     # Permite leitura de processos e CPU (/proc)
      - hardware-observe   # Permite leitura de sensores e hardware (/sys)
      - mount-observe      # Permite mapear discos e partições montadas

parts:
  system-monitor:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart